sudo: required
services:
  - docker

before_install:
  - docker build -t sarithekanayake/docker-react -f Dockerfile.dev .

script:
  - docker run sarithekanayake/docker-react npm run test -- --coverage